<a href="https://colab.research.google.com/github/Nitesh-061/Fake_News_Classifier_Using_LSTM/blob/main/FakeNewsClassifierUsingLSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
import pandas as pd


In [36]:
df=pd.read_csv('/content/drive/My Drive/Colab Notebooks/DataSet/FakeNewsClassifiers/train.csv/train.csv')

In [37]:
df.head()

id  ... label
0   0  ...     1
1   1  ...     0
2   2  ...     1
3   3  ...     1
4   4  ...     1

[5 rows x 5 columns]

In [38]:
import tensorflow as tf

In [39]:
tf.__version__

'2.3.0'

In [40]:
df=df.dropna()

In [41]:
X=df.drop('label',axis=1)
y=df['label']

In [42]:
X.shape

(18285, 4)

In [43]:
y.shape

(18285,)

In [44]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [45]:
### Vocabulary size
voc_size=5000

Onehot Representation

In [46]:
messages=X.copy()

In [47]:
messages.head()

id  ...                                               text
0   0  ...  House Dem Aide: We Didn’t Even See Comey’s Let...
1   1  ...  Ever get the feeling your life circles the rou...
2   2  ...  Why the Truth Might Get You Fired October 29, ...
3   3  ...  Videos 15 Civilians Killed In Single US Airstr...
4   4  ...  Print \nAn Iranian woman has been sentenced to...

[5 rows x 4 columns]

In [48]:
messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [49]:
messages.reset_index(inplace=True)

In [50]:
import nltk
import re
from nltk.corpus import stopwords

In [51]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [52]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

Streaming output truncated to the last 5000 lines.
13286
13287
13288
13289
13290
13291
13292
13293
13294
13295
13296
13297
13298
13299
13300
13301
13302
13303
13304
13305
13306
13307
13308
13309
13310
13311
13312
13313
13314
13315
13316
13317
13318
13319
13320
13321
13322
13323
13324
13325
13326
13327
13328
13329
13330
13331
13332
13333
13334
13335
13336
13337
13338
13339
13340
13341
13342
13343
13344
13345
13346
13347
13348
13349
13350
13351
13352
13353
13354
13355
13356
13357
13358
13359
13360
13361
13362
13363
13364
13365
13366
13367
13368
13369
13370
13371
13372
13373
13374
13375
13376
13377
13378
13379
13380
13381
13382
13383
13384
13385
13386
13387
13388
13389
13390
13391
13392
13393
13394
13395
13396
13397
13398
13399
13400
13401
13402
13403
13404
13405
13406
13407
13408
13409
13410
13411
13412
13413
13414
13415
13416
13417
13418
13419
13420
13421
13422
13423
13424
13425
13426
13427
13428
13429
13430
13431
13432
13433
13434
13435
13436
13437
13438
13439
13440
13441
13442
13443
1

In [54]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [55]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[771, 1705, 2798, 1612, 4467, 2585, 2953, 393, 3514, 1570],
 [1305, 1969, 3705, 4063, 647, 396, 3026],
 [1564, 4253, 4239, 2183],
 [2089, 2951, 4425, 3091, 2196, 2191],
 [1206, 647, 195, 4254, 684, 4797, 647, 3591, 492, 4825],
 [1320,
  1681,
  1755,
  3021,
  4807,
  3088,
  517,
  2671,
  3506,
  2328,
  4418,
  4924,
  4601,
  3957,
  3026],
 [4471, 219, 3264, 1944, 4748, 3794, 1954, 142, 4129, 4337, 2930],
 [1218, 4529, 1121, 4398, 2322, 4560, 3088, 1061, 4129, 4337, 2930],
 [964, 3298, 2266, 2014, 3589, 1380, 3994, 694, 3088, 3217],
 [2324, 4194, 1205, 3948, 154, 3146, 29, 1566],
 [613, 1668, 2896, 880, 2939, 2423, 14, 4952, 2169, 3488, 1323],
 [3091, 4410, 4467, 1380, 3088, 2322],
 [2, 4525, 1725, 390, 409, 4343, 2321, 2314, 1792],
 [600, 2995, 4141, 1669, 2429, 2226, 4019, 4129, 4337, 2930],
 [668, 1920, 769, 2671, 1152, 4129, 4337, 2930],
 [2165, 4213, 2251, 4179, 372, 448, 4255, 4714, 3081, 1412],
 [583, 3438, 1969],
 [3337, 3790, 4788, 4965, 3088, 128, 3137, 3026],
 [3533, 4

Embedding Representation

In [56]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ...  393 3514 1570]
 [   0    0    0 ...  647  396 3026]
 [   0    0    0 ... 4253 4239 2183]
 ...
 [   0    0    0 ... 4129 4337 2930]
 [   0    0    0 ... 2887   93 1694]
 [   0    0    0 ... 3993 4404 1806]]


In [57]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,  771,
       1705, 2798, 1612, 4467, 2585, 2953,  393, 3514, 1570], dtype=int32)

In [61]:
## Creating model
from tensorflow.keras.layers import Dropout
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_4 (Embedding)      (None, 20, 40)            200000    
_________________________________________________________________
dropout (Dropout)            (None, 20, 40)            0         
_________________________________________________________________
lstm_2 (LSTM)                (None, 100)               56400     
_________________________________________________________________
dropout_1 (Dropout)          (None, 100)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [62]:
len(embedded_docs),y.shape

(18285, (18285,))

In [63]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [64]:
X_final.shape,y_final.shape

((18285, 20), (18285,))

In [65]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

Model Training

In [66]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 2s 10ms/step - loss: 0.3599 - accuracy: 0.8304 - val_loss: 0.1999 - val_accuracy: 0.9153
Epoch 2/10
192/192 [==============================] - 2s 8ms/step - loss: 0.1526 - accuracy: 0.9392 - val_loss: 0.2042 - val_accuracy: 0.9203
Epoch 3/10
192/192 [==============================] - 2s 8ms/step - loss: 0.1127 - accuracy: 0.9565 - val_loss: 0.2124 - val_accuracy: 0.9196
Epoch 4/10
192/192 [==============================] - 2s 8ms/step - loss: 0.0859 - accuracy: 0.9675 - val_loss: 0.2308 - val_accuracy: 0.9138
Epoch 5/10
192/192 [==============================] - 2s 8ms/step - loss: 0.0660 - accuracy: 0.9771 - val_loss: 0.2762 - val_accuracy: 0.9132
Epoch 6/10
192/192 [==============================] - 2s 8ms/step - loss: 0.0457 - accuracy: 0.9847 - val_loss: 0.3332 - val_accuracy: 0.9122
Epoch 7/10
192/192 [==============================] - 1s 8ms/step - loss: 0.0311 - accuracy: 0.9904 - val_loss: 0.4034 - val_accuracy: 0.9064
Epoch

In [67]:
y_pred=model.predict_classes(X_test)

In [68]:
from sklearn.metrics import confusion_matrix

In [69]:
confusion_matrix(y_test,y_pred)

array([[3136,  283],
       [ 300, 2316]])

In [70]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9033968516984259